### ISSUE TITLE
BUG: Data munging issue when running the example CAISO-ERCOT-IC

### ISSUE THREAD

**Issue by amanmajid** [transition-zero/tz-osemosys#90]
### Checklist

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of tz-osemosys.

- [X] I have confirmed this bug exists on the main branch of tz-osemosys.

### Reproducible Example

I am loading the example `CAISO-ERCOT-IC` model as below:

```
from tz.osemosys import Model
model = Model.from_yaml("examples/CAISO-ERCOT-IC/")

```

This loads in the model correctly, I think. Next, I attempt to solve the model by running: `model.solve()`. This results in the error below.

![Screenshot 2024-04-24 at 15 10 01](https://github.com/transition-zero/tz-osemosys/assets/39566844/a8b10390-2289-4ada-9ffb-10d78d6fe5f9)

### Issue Description

This appears to be a data-munging issue, which only appears to be triggered when the model is loaded as above. 

### Expected Behavior

We should be able to solve the model after loading.

**Comment by edwardxtg** [comment]
Closed.

https://github.com/transition-zero/tz-osemosys/pull/98
